apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: v1.6.4
networking:
  podSubnet: 10.244.0.0/16
etcd:
  endpoints:
  - http://${HOST_IP}:2379
  - http://${HOST_IP}:2379
  - http://${HOST_IP}:2379
